import type { Role } from "@/lib/role"

/**
 * Week 40, the first list.
 * Surviving roles from 29 Sep, plus the postings confirmed on 2 Oct.
 * A closed role moves to lib/archive.ts. It does not stay here.
 */
export const week40: Role[] = [
  {
    id: "vercel-design-engineer",
    company: "Vercel",
    title: "Design Engineer",
    band: "ship",
    prong: "frontend",
    also: "judgment",
    seat: "team",
    href: "https://vercel.com/careers/design-engineer-us-6129441004",
    why: "Production UI in a product engineers already own. A prototype is not the proof they named.",
    salary: "$208,000–$312,000 in San Francisco",
    where: "Remote, United States",
    week: "2026-W40",
  },
  {
    id: "linear-web-brand",
    company: "Linear",
    title: "Design Engineer (Web & Brand)",
    band: "ship",
    prong: "motion",
    also: "frontend",
    seat: "team",
    href: "https://linear.app/careers/f04f398b-6320-499d-8a60-290239d62da8",
    why: "Web and brand. They grade taste and shipped interactive pages.",
    where: "Remote, North America",
    week: "2026-W40",
  },
  {
    id: "stripe-expansion",
    company: "Stripe",
    title: "Design Engineer, Expansion",
    band: "ship",
    prong: "motion",
    also: "systems",
    seat: "team",
    href: "https://stripe.com/jobs/search?gh_jid=8212314",
    why: "Campaign pages and the design system, beside people who already build the site.",
    salary: "$157,300–$235,900",
    where: "Remote, United States",
    week: "2026-W40",
  },
  {
    id: "stripe-presence",
    company: "Stripe",
    title: "Design Engineer, Presence",
    band: "ship",
    prong: "motion",
    also: "systems",
    seat: "team",
    href: "https://stripe.com/jobs/listing/design-engineer-presence/7144975",
    why: "Brand surfaces and motion. The posting names the libraries other people consume.",
    week: "2026-W40",
  },
  {
    id: "coderabbit",
    company: "CodeRabbit",
    title: "Design Engineer",
    band: "ship",
    prong: "judgment",
    also: "systems",
    seat: "team",
    href: "https://jobs.ashbyhq.com/coderabbit/bb95e939-0da5-4480-b162-c6ae82db3c12",
    why: "Product UI across the editor, the CLI, and the web. Design systems are named.",
    salary: "$175,000–$225,000 plus equity",
    where: "San Francisco, hybrid",
    week: "2026-W40",
  },
  {
    id: "ramp",
    company: "Ramp",
    title: "Design Engineer",
    band: "ship",
    prong: "systems",
    also: "judgment",
    seat: "team",
    href: "https://jobs.ashbyhq.com/ramp/b68aca53-16c0-4ced-ab1d-e8beb2940b4f",
    why: "Shipped product UI, and components other people reuse.",
    salary: "$172,000–$440,000 plus equity",
    where: "New York, hybrid",
    week: "2026-W40",
  },
  {
    id: "circleback",
    company: "Circleback",
    title: "Design Engineer",
    band: "ship",
    prong: "frontend",
    also: "systems",
    seat: "team",
    href: "https://jobs.ashbyhq.com/circleback/832f884e-b912-41e0-988f-d5de0243ed04",
    why: "You would own the product surface and the design system, beside a small engineering team.",
    salary: "$170,000–$280,000 plus equity",
    where: "San Francisco, onsite",
    week: "2026-W40",
  },
  {
    id: "idler",
    company: "idler",
    title: "Design Engineer",
    band: "spike",
    prong: "judgment",
    also: "motion",
    seat: "solo",
    href: "https://jobs.ashbyhq.com/idler/199e6e98-c12f-494f-8cd1-eba950d45860",
    why: "You would own the visual system and the implementation.",
    salary: "$125,000–$300,000 plus equity",
    where: "San Francisco, onsite",
    week: "2026-W40",
  },
  {
    id: "ashby-americas",
    company: "Ashby",
    title: "Design Engineer, Americas",
    band: "ship",
    prong: "judgment",
    also: "frontend",
    seat: "team",
    href: "https://jobs.ashbyhq.com/ashby/fd86edd7-3af0-4977-a61a-215212c296fa",
    why: "Design and code, shipped to users. Engineers are already on the team.",
    salary: "$126,000–$250,000 plus equity",
    where: "Remote, United States",
    week: "2026-W40",
  },
  {
    id: "ashby-uk",
    company: "Ashby",
    title: "Design Engineer, UK",
    band: "ship",
    prong: "judgment",
    also: "frontend",
    seat: "team",
    href: "https://jobs.ashbyhq.com/Ashby/cb45928e-c7c7-4163-84d0-a962755a3593",
    why: "The same seat as the Americas posting. They expect code in production.",
    salary: "£56,000–£149,000 plus equity",
    where: "Remote, United Kingdom",
    week: "2026-W40",
  },
  {
    id: "ternion",
    company: "Ternion",
    title: "Founding Design Engineer (AI-Native)",
    band: "spike",
    prong: "frontend",
    also: "systems",
    seat: "solo",
    href: "https://jobs.ashbyhq.com/ternion-security/71c804a4-b005-4778-8f9e-16f5905781f0",
    why: "No designer on the team. The posting is the whole UI.",
    salary: "$170,000–$220,000 plus equity",
    where: "Bellevue, onsite",
    week: "2026-W40",
  },
  {
    id: "granola-product-designer",
    company: "Granola",
    title: "Product Designer",
    band: "prototype",
    prong: "motion",
    also: "systems",
    seat: "team",
    href: "https://jobs.ashbyhq.com/granola/0897636e-e415-493e-b501-7c610ea72eff",
    why: "They sit with engineers and prototype in Figma or code. They grade what shipped.",
    salary: "£110,000–£150,000 plus equity",
    where: "London, onsite",
    week: "2026-W40",
  },
  {
    id: "granola-design-engineer",
    company: "Granola",
    title: "Design Engineer",
    band: "ship",
    prong: "systems",
    also: "frontend",
    seat: "team",
    href: "https://jobs.ashbyhq.com/granola/77cf40dd-0a11-4b23-ab9d-ff9d9d1e5f41",
    why: "Production UI and the design system, in Figma and in code, beside design and engineering.",
    salary: "£100,000–£130,000 plus equity",
    where: "London, onsite",
    week: "2026-W40",
  },
  {
    id: "elevenlabs-product-designer",
    company: "ElevenLabs",
    title: "Product Designer",
    band: "taste",
    prong: "judgment",
    seat: "team",
    href: "https://jobs.ashbyhq.com/elevenlabs/89da00ec-11b0-4359-913b-c3a89c1013bc",
    why: "They grade a rough Figma and past work. Frontend engineers are a separate group.",
    where: "Remote",
    week: "2026-W40",
  },
  {
    id: "revenuecat",
    company: "RevenueCat",
    title: "Senior Design Engineer",
    band: "ship",
    prong: "frontend",
    also: "systems",
    seat: "team",
    href: "https://jobs.ashbyhq.com/revenuecat/a897e317-9c65-46d5-ace3-25ec6f7b4a0c",
    why: "They turn design intent into production UI, beside a design team and engineers.",
    salary: "$220,000 plus equity",
    where: "Remote, Americas, APAC, and EMEA",
    week: "2026-W40",
  },
  {
    id: "figma-roundtripping",
    company: "Figma",
    title: "Product Designer, Roundtripping",
    band: "prototype",
    prong: "judgment",
    seat: "team",
    href: "https://job-boards.greenhouse.io/figma/jobs/6193686004",
    why: "They grade flows, prototypes, and visuals. HTML and CSS is a plus.",
    where: "London, or remote in the United Kingdom",
    week: "2026-W40",
  },
  {
    id: "boski",
    company: "Boski",
    title: "Founding Design Engineer",
    band: "spike",
    prong: "frontend",
    also: "systems",
    seat: "solo",
    href: "https://www.boski.com/careers/founding-design-engineer",
    why: "You would own how it looks and works, then build it, across web and iOS.",
    salary: "$100,000–$120,000 and 2% equity",
    where: "Warsaw",
    week: "2026-W40",
  },
]
