import type { Role } from "@/lib/role"

/**
 * Week 40, the first list.
 * Surviving roles from 29 Sep, plus the postings confirmed on 2 Oct.
 * The fund pass the same day added the seats still open on the company page.
 * Wise’s six product designer seats were filed on 4 Oct, still inside this week.
 * A closed role moves to lib/archive.ts. It does not stay here.
 */
export const week40: Role[] = [
  {
    id: "vercel-design-engineer",
    company: "Vercel",
    title: "Design Engineer",
    band: "ship",
    prong: "frontend",
    also: "judgment",
    seat: "team",
    href: "https://vercel.com/careers/design-engineer-us-6129441004",
    why: "Production UI in a product engineers already own. A prototype is not the proof they named.",
    salary: "$208,000–$312,000 in San Francisco",
    where: "Remote, United States",
    week: "2026-W40",
  },
  {
    id: "linear-web-brand",
    company: "Linear",
    title: "Design Engineer (Web & Brand)",
    band: "ship",
    prong: "motion",
    also: "frontend",
    seat: "team",
    href: "https://linear.app/careers/f04f398b-6320-499d-8a60-290239d62da8",
    why: "Web and brand. They grade taste and shipped interactive pages.",
    where: "Remote, North America",
    week: "2026-W40",
  },
  {
    id: "stripe-expansion",
    company: "Stripe",
    title: "Design Engineer, Expansion",
    band: "ship",
    prong: "motion",
    also: "systems",
    seat: "team",
    href: "https://stripe.com/jobs/search?gh_jid=8212314",
    why: "Campaign pages and the design system, beside people who already build the site.",
    salary: "$157,300–$235,900",
    where: "Remote, United States",
    week: "2026-W40",
  },
  {
    id: "stripe-presence",
    company: "Stripe",
    title: "Design Engineer, Presence",
    band: "ship",
    prong: "motion",
    also: "systems",
    seat: "team",
    href: "https://stripe.com/jobs/listing/design-engineer-presence/7144975",
    why: "Brand surfaces and motion. The posting names the libraries other people consume.",
    week: "2026-W40",
  },
  {
    id: "coderabbit",
    company: "CodeRabbit",
    title: "Design Engineer",
    band: "ship",
    prong: "judgment",
    also: "systems",
    seat: "team",
    href: "https://jobs.ashbyhq.com/coderabbit/bb95e939-0da5-4480-b162-c6ae82db3c12",
    why: "Product UI across the editor, the CLI, and the web. Design systems are named.",
    salary: "$175,000–$225,000 plus equity",
    where: "San Francisco, hybrid",
    week: "2026-W40",
  },
  {
    id: "ramp",
    company: "Ramp",
    title: "Design Engineer",
    band: "ship",
    prong: "systems",
    also: "judgment",
    seat: "team",
    href: "https://jobs.ashbyhq.com/ramp/b68aca53-16c0-4ced-ab1d-e8beb2940b4f",
    why: "Shipped product UI, and components other people reuse.",
    salary: "$172,000–$440,000 plus equity",
    where: "New York, hybrid",
    week: "2026-W40",
  },
  {
    id: "circleback",
    company: "Circleback",
    title: "Design Engineer",
    band: "ship",
    prong: "frontend",
    also: "systems",
    seat: "team",
    href: "https://jobs.ashbyhq.com/circleback/832f884e-b912-41e0-988f-d5de0243ed04",
    why: "You would own the product surface and the design system, beside a small engineering team.",
    salary: "$170,000–$280,000 plus equity",
    where: "San Francisco, onsite",
    week: "2026-W40",
  },
  {
    id: "idler",
    company: "idler",
    title: "Design Engineer",
    band: "spike",
    prong: "judgment",
    also: "motion",
    seat: "solo",
    href: "https://jobs.ashbyhq.com/idler/199e6e98-c12f-494f-8cd1-eba950d45860",
    why: "You would own the visual system and the implementation.",
    salary: "$125,000–$300,000 plus equity",
    where: "San Francisco, onsite",
    week: "2026-W40",
  },
  {
    id: "ashby-americas",
    company: "Ashby",
    title: "Design Engineer, Americas",
    band: "ship",
    prong: "judgment",
    also: "frontend",
    seat: "team",
    href: "https://jobs.ashbyhq.com/ashby/fd86edd7-3af0-4977-a61a-215212c296fa",
    why: "Design and code, shipped to users. Engineers are already on the team.",
    salary: "$126,000–$250,000 plus equity",
    where: "Remote, United States",
    week: "2026-W40",
  },
  {
    id: "ashby-uk",
    company: "Ashby",
    title: "Design Engineer, UK",
    band: "ship",
    prong: "judgment",
    also: "frontend",
    seat: "team",
    href: "https://jobs.ashbyhq.com/Ashby/cb45928e-c7c7-4163-84d0-a962755a3593",
    why: "The same seat as the Americas posting. They expect code in production.",
    salary: "£56,000–£149,000 plus equity",
    where: "Remote, United Kingdom",
    week: "2026-W40",
  },
  {
    id: "ternion",
    company: "Ternion",
    title: "Founding Design Engineer (AI-Native)",
    band: "spike",
    prong: "frontend",
    also: "systems",
    seat: "solo",
    href: "https://jobs.ashbyhq.com/ternion-security/71c804a4-b005-4778-8f9e-16f5905781f0",
    why: "No designer on the team. The posting is the whole UI.",
    salary: "$170,000–$220,000 plus equity",
    where: "Bellevue, onsite",
    week: "2026-W40",
  },
  {
    id: "granola-product-designer",
    company: "Granola",
    title: "Product Designer",
    band: "prototype",
    prong: "motion",
    also: "systems",
    seat: "team",
    href: "https://jobs.ashbyhq.com/granola/0897636e-e415-493e-b501-7c610ea72eff",
    why: "They sit with engineers and prototype in Figma or code. They grade what shipped.",
    salary: "£110,000–£150,000 plus equity",
    where: "London, onsite",
    week: "2026-W40",
  },
  {
    id: "granola-design-engineer",
    company: "Granola",
    title: "Design Engineer",
    band: "ship",
    prong: "systems",
    also: "frontend",
    seat: "team",
    href: "https://jobs.ashbyhq.com/granola/77cf40dd-0a11-4b23-ab9d-ff9d9d1e5f41",
    why: "Production UI and the design system, in Figma and in code, beside design and engineering.",
    salary: "£100,000–£130,000 plus equity",
    where: "London, onsite",
    week: "2026-W40",
  },
  {
    id: "elevenlabs-product-designer",
    company: "ElevenLabs",
    title: "Product Designer",
    band: "taste",
    prong: "judgment",
    seat: "team",
    href: "https://jobs.ashbyhq.com/elevenlabs/89da00ec-11b0-4359-913b-c3a89c1013bc",
    why: "They grade a rough Figma and past work. Frontend engineers are a separate group.",
    where: "Remote",
    week: "2026-W40",
  },
  {
    id: "revenuecat",
    company: "RevenueCat",
    title: "Senior Design Engineer",
    band: "ship",
    prong: "frontend",
    also: "systems",
    seat: "team",
    href: "https://jobs.ashbyhq.com/revenuecat/a897e317-9c65-46d5-ace3-25ec6f7b4a0c",
    why: "They turn design intent into production UI, beside a design team and engineers.",
    salary: "$220,000 plus equity",
    where: "Remote, Americas, APAC, and EMEA",
    week: "2026-W40",
  },
  {
    id: "figma-roundtripping",
    company: "Figma",
    title: "Product Designer, Roundtripping",
    band: "prototype",
    prong: "judgment",
    seat: "team",
    href: "https://job-boards.greenhouse.io/figma/jobs/6193686004",
    why: "They grade flows, prototypes, and visuals. HTML and CSS is a plus.",
    where: "London, or remote in the United Kingdom",
    week: "2026-W40",
  },
  {
    id: "boski",
    company: "Boski",
    title: "Founding Design Engineer",
    band: "spike",
    prong: "frontend",
    also: "systems",
    seat: "solo",
    href: "https://www.boski.com/careers/founding-design-engineer",
    why: "You would own how it looks and works, then build it, across web and iOS.",
    salary: "$100,000–$120,000 and 2% equity",
    where: "Warsaw",
    week: "2026-W40",
  },
  {
    id: "sequence-product-designer",
    company: "Sequence",
    title: "Senior Product Designer",
    band: "prototype",
    prong: "judgment",
    seat: "team",
    href: "https://jobs.ashbyhq.com/sequence/399b4d28-a076-4675-a9ac-1bb14c09b965",
    why: "One of the first designers. They grade prototypes of billing flows. Product and engineering are already there.",
    salary: "£80,000–£95,000 plus equity",
    where: "London, hybrid",
    week: "2026-W40",
  },
  {
    id: "linear-principal-product-designer",
    company: "Linear",
    title: "Principal Product Designer",
    band: "prototype",
    prong: "judgment",
    also: "systems",
    seat: "team",
    href: "https://linear.app/careers/ba8a41d2-4198-481a-a7f4-e09c5364ff7f",
    why: "They grade mockups, prototypes, and high-fidelity visuals. Engineers are paired on the project.",
    where: "Remote, North America and Europe",
    week: "2026-W40",
  },
  {
    id: "chromatic-product-designer",
    company: "Chromatic",
    title: "Senior Product Designer",
    band: "ship",
    prong: "frontend",
    also: "systems",
    seat: "team",
    href: "https://jobs.ashbyhq.com/chromatic/75693ed5-b8de-4cf0-a38a-ac259a6f05ef",
    why: "They want prototypes and production UI in React, and a design system engineers and agents use.",
    salary: "$143,000–$162,000 plus equity",
    where: "Remote, North America or Europe",
    week: "2026-W40",
  },
  {
    id: "edra-product-designer",
    company: "Edra",
    title: "Founding Product Designer",
    band: "prototype",
    prong: "judgment",
    also: "systems",
    seat: "team",
    href: "https://jobs.ashbyhq.com/edra/97b34fd9-4f34-45b5-b52a-67085b65e9b2",
    why: "They grade wireframes, prototypes, and high-fidelity screens. Engineers ship.",
    where: "London, onsite",
    week: "2026-W40",
  },
  {
    id: "tldraw-design-engineer",
    company: "tldraw",
    title: "Design Engineer",
    band: "ship",
    prong: "motion",
    also: "frontend",
    seat: "team",
    href: "https://jobs.ashbyhq.com/tldraw/c52007ee-bac0-4176-a5f0-48fe6e1fe854",
    why: "A product designer who builds. Prototypes in code, then production with engineers.",
    where: "London, hybrid",
    week: "2026-W40",
  },
  {
    id: "cal-design-engineer",
    company: "Cal.com",
    title: "Senior Product Design Engineer",
    band: "ship",
    prong: "systems",
    also: "frontend",
    seat: "team",
    href: "https://cal.com/jobs/senior-product-designer",
    why: "They grade production components and the design system. A product engineer picks them up. Motion is named.",
    salary: "$100,000–$150,000 plus equity",
    where: "Remote",
    week: "2026-W40",
  },
  {
    id: "circle-product-designer",
    company: "Circle",
    title: "Lead Product Designer",
    band: "prototype",
    prong: "judgment",
    seat: "team",
    href: "https://circle.so/careers/ashby--130695ad-687e-4c49-976f-eb46f9b45ac9",
    why: "They grade prototypes and the flow. Design engineers and product engineers ship.",
    salary: "$140,000–$170,000 plus equity",
    where: "Remote",
    week: "2026-W40",
  },
  {
    id: "circle-marketplace",
    company: "Circle",
    title: "Lead Product Designer, Marketplace",
    band: "prototype",
    prong: "judgment",
    seat: "team",
    href: "https://circle.so/careers/ashby--c6fd95f5-d7f8-4297-be2d-e91d19052469",
    why: "The same lead seat, on Discover. They grade the marketplace flow, then engineers ship.",
    where: "Remote",
    week: "2026-W40",
  },
  {
    id: "lemni-design-engineer",
    company: "Lemni",
    title: "Senior Design Engineer",
    band: "ship",
    prong: "frontend",
    also: "systems",
    seat: "team",
    href: "https://www.lemni.com/company/sr-design-engineer",
    why: "They grade prototypes, then the React that ships. Engineering is beside you.",
    where: "Amsterdam",
    week: "2026-W40",
  },
  {
    id: "paper-design-engineer",
    company: "Paper",
    title: "Design Engineer",
    band: "ship",
    prong: "frontend",
    seat: "team",
    href: "https://paper.design/blog/2026-design-engineer",
    why: "Principal. You design and implement the UI. The team is remote across the Americas, Europe, and Australia.",
    where: "Remote, Americas, Europe, and Australia",
    week: "2026-W40",
  },
  {
    id: "lovable-product-designer",
    company: "Lovable",
    title: "Product Designer",
    band: "prototype",
    prong: "judgment",
    also: "systems",
    seat: "team",
    href: "https://lovable.dev/careers/product-designer-cf78be",
    why: "They grade flows and high-fidelity mockups. Shipping the code is a bonus.",
    where: "Stockholm, onsite",
    week: "2026-W40",
  },
  {
    id: "voize-product-designer",
    company: "voize",
    title: "Senior Product Designer",
    band: "prototype",
    prong: "judgment",
    also: "systems",
    seat: "team",
    href: "https://jobs.ashbyhq.com/Voize/a8e73353-60bf-4aba-953e-1f209d5e969e",
    why: "They grade mobile flows and production-ready UI. Product and engineering implement.",
    where: "Berlin, or remote across Germany",
    week: "2026-W40",
  },
  {
    id: "hera-product-designer",
    company: "Hera",
    title: "Founding Product Designer",
    band: "prototype",
    prong: "judgment",
    also: "systems",
    seat: "team",
    href: "https://www.ycombinator.com/companies/hera-video/jobs/3YpF3GY-founding-product-designer",
    why: "They grade prototypes, a design system, and pixel-level execution. Engineering is beside you.",
    salary: "€80,000–€130,000, 0.75%–1.50%",
    where: "Berlin, onsite",
    week: "2026-W40",
  },
  {
    id: "telli-design-lead",
    company: "telli",
    title: "Design Lead",
    band: "taste",
    prong: "judgment",
    seat: "team",
    href: "https://www.ycombinator.com/companies/telli/jobs/7k8HRXE-founding-design-engineer",
    why: "The proof is the portfolio. A designer who has never written production code can apply.",
    salary: "€75,000–€160,000 plus equity",
    where: "Berlin, onsite",
    week: "2026-W40",
  },
  {
    id: "mercura-design-engineer",
    company: "Mercura",
    title: "Design Engineer",
    band: "ship",
    prong: "frontend",
    also: "judgment",
    seat: "team",
    href: "https://jobs.ashbyhq.com/mercura/ac4afb1a-7a79-49b4-a868-eac4e11b5214",
    why: "You design it and write the production React. You are the second designer. German is required.",
    where: "Munich, onsite",
    week: "2026-W40",
  },
  {
    id: "mirelo-product-designer",
    company: "Mirelo",
    title: "Principal Product Designer",
    band: "prototype",
    prong: "judgment",
    seat: "team",
    href: "https://jobs.ashbyhq.com/mirelo/3a701e14-3102-472d-9ccf-b7dafc447e39",
    why: "The first product designer. They grade end-to-end flows and high-craft interfaces.",
    where: "Hybrid, Germany",
    week: "2026-W40",
  },
  {
    id: "marker-product-designer",
    company: "Marker",
    title: "Product Designer",
    band: "taste",
    prong: "systems",
    also: "judgment",
    seat: "team",
    href: "https://marker.page/jobs/product-designer",
    why: "They grade a portfolio and the design system. You are not expected to be the engineer.",
    salary: "£60,000–£80,000, up to £100,000, plus equity",
    where: "London hub",
    week: "2026-W40",
  },
  {
    id: "wise-money-movement",
    company: "Wise",
    title: "Staff Product Designer - Money Movement",
    band: "prototype",
    prong: "systems",
    also: "judgment",
    seat: "team",
    href: "https://jobs.smartrecruiters.com/Wise/744000152893635-staff-product-designer-money-movement",
    why: "They grade prototypes and a design system. You are the most senior designer on the squad.",
    salary: "£102,000–£133,000",
    where: "London",
    week: "2026-W40",
  },
  {
    id: "wise-business",
    company: "Wise",
    title: "Staff Product Designer - Wise Business",
    band: "prototype",
    prong: "systems",
    also: "judgment",
    seat: "team",
    href: "https://jobs.smartrecruiters.com/Wise/744000152184429-staff-product-designer-wise-business",
    why: "They grade a portfolio and prototypes. Engineers are on the squad.",
    salary: "£102,000–£133,000",
    where: "London",
    week: "2026-W40",
  },
  {
    id: "wise-assistant",
    company: "Wise",
    title: "Staff Product Designer - Wise Assistant Experience",
    band: "taste",
    prong: "systems",
    also: "judgment",
    seat: "team",
    href: "https://jobs.smartrecruiters.com/Wise/744000142130824-staff-product-designer-wise-assistant-experience",
    why: "They grade a design-system portfolio. Prototyping in code helps, and it is not required.",
    salary: "£102,000–£133,000",
    where: "London",
    week: "2026-W40",
  },
  {
    id: "wise-fincrime",
    company: "Wise",
    title: "Staff Product Designer",
    band: "prototype",
    prong: "judgment",
    also: "systems",
    seat: "team",
    href: "https://jobs.smartrecruiters.com/Wise/744000129717894-staff-product-designer",
    why: "FinCrime. They grade a portfolio and prototypes of the flows. The place is London or Budapest.",
    salary: "£101,000–£131,000",
    where: "London or Budapest",
    week: "2026-W40",
  },
  {
    id: "wise-verification",
    company: "Wise",
    title: "Senior Product Designer, Verification",
    band: "taste",
    prong: "judgment",
    also: "systems",
    seat: "team",
    href: "https://wise.jobs/job/senior-product-designer-verification-in-london-jid-3959",
    why: "They grade design craft on the verification journeys. Engineering partners deliver the work.",
    salary: "£72,000–£105,000",
    where: "London",
    week: "2026-W40",
  },
  {
    id: "wise-credit",
    company: "Wise",
    title: "Senior Product Designer - Spend - Credit",
    band: "prototype",
    prong: "judgment",
    also: "systems",
    seat: "team",
    href: "https://jobs.smartrecruiters.com/Wise/744000152440329-senior-product-designer-spend-credit",
    why: "They want the credit journeys, not a visual file alone. Engineering sits beside you.",
    salary: "£72,000–£105,000",
    where: "London",
    week: "2026-W40",
  },
]
