import type { Company } from "@/lib/company"

/**
 * Company list, 3 Oct 2026.
 * The tools on the machine, early teams in the same corner,
 * then the Fast Company 2026 AI pass.
 * Stage is the last public round. The check is stage-check.md.
 * Place and how they work are copied only when a posting or a round already said them.
 * Pre-seed is empty until a public pre-seed round is in hand.
 * The AI names left off are recorded in roadmap.md.
 * Recraft was filed the same day, from the company site and their Series B post.
 * The AI designer seat stayed off the role list. The place is four countries, and the seat grades taste on the model.
 * Marker and Meticulous were filed the same evening.
 * Marker’s seed is in the press, not on their site, so the stage stays off.
 */
export const companies: Company[] = [
  {
    id: "onlook",
    name: "Onlook",
    href: "https://onlook.com",
    why: "A visual editor on the running interface. One founder is a designer.",
    stage: "seed",
    round: "YC, Winter 2025",
    where: "San Francisco",
  },
  {
    id: "semiotic",
    name: "Semiotic",
    href: "https://semiotic.com",
    why: "Three people. Studio-grade pages, instead of an agency wait.",
    stage: "seed",
    round: "YC, Fall 2025",
    where: "San Francisco",
  },
  {
    id: "tldraw",
    name: "tldraw",
    href: "https://tldraw.com",
    why: "The infinite canvas. The design engineer seat is London, hybrid.",
    stage: "later",
    round: "Series A, Apr 2025",
    work: "hybrid",
    where: "London, hybrid",
  },
  {
    id: "amie",
    name: "Amie",
    href: "https://amie.so",
    why: "A calendar with a point of view. The public round is still the seed.",
    stage: "seed",
    round: "Seed, 2022",
  },
  {
    id: "opal",
    name: "Opal",
    href: "https://www.opal.so",
    why: "The screen-time app on the machine.",
    stage: "seed",
    round: "$10M, May 2026",
  },
  {
    id: "figma",
    name: "Figma",
    href: "https://www.figma.com",
    why: "The design tool on the machine.",
    stage: "later",
  },
  {
    id: "openai",
    name: "OpenAI",
    href: "https://openai.com",
    why: "ChatGPT is the model on the machine.",
    stage: "later",
  },
  {
    id: "xai",
    name: "xAI",
    href: "https://x.ai",
    why: "Grok is the model on the machine.",
    stage: "later",
  },
  {
    id: "x",
    name: "X",
    href: "https://x.com",
    why: "The public room. Replies live here.",
    stage: "later",
  },
  {
    id: "cursor",
    name: "Cursor",
    href: "https://cursor.com",
    why: "The editor on the machine. The US seat left the role list. The company stays.",
    stage: "later",
    round: "Series D, Nov 2025",
  },
  {
    id: "vercel",
    name: "Vercel",
    href: "https://vercel.com",
    why: "The place the work gets deployed.",
    stage: "later",
    round: "Series F, Sep 2025",
  },
  {
    id: "cosmos",
    name: "Cosmos",
    href: "https://www.cosmos.so",
    why: "Visual references, collected in one place.",
    stage: "later",
    round: "Series A, Jan 2026",
    where: "New York",
  },
  {
    id: "granola",
    name: "Granola",
    href: "https://www.granola.ai",
    why: "Meeting notes, without a bot in the room.",
    stage: "later",
    round: "Series C, Mar 2026",
    work: "room",
    where: "London, onsite",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    href: "https://elevenlabs.io",
    why: "The voice product. The product designer seat can close. The company stays.",
    stage: "later",
    round: "Series C, Jan 2025",
    work: "remote",
    where: "Remote",
  },
  {
    id: "paper",
    name: "Paper",
    href: "https://paper.design",
    why: "A design tool for software that has to stand out.",
    stage: "later",
    round: "Series A, Jul 2026",
    work: "remote",
    where: "Remote, Americas, Europe, and Australia",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    href: "https://www.anthropic.com",
    why: "Claude Code is the coding agent beside the editor.",
    stage: "later",
    where: "San Francisco",
  },
  {
    id: "world-labs",
    name: "World Labs",
    href: "https://www.worldlabs.ai",
    why: "Marble turns an image, a video, or text into a 3D world.",
    stage: "later",
    round: "$1B, Feb 2026",
  },
  {
    id: "runway",
    name: "Runway",
    href: "https://runwayml.com",
    why: "Production video from a prompt, with the same character across shots.",
    stage: "later",
    round: "$315M, Feb 2026",
  },
  {
    id: "factory",
    name: "Factory",
    href: "https://factory.ai",
    why: "Agents that plan and ship software, in the terminal and in Slack.",
    stage: "later",
    round: "$200M, Sep 2026",
    where: "San Francisco",
  },
  {
    id: "hume",
    name: "Hume",
    href: "https://www.hume.ai",
    why: "A voice that carries emotion. The same corner as ElevenLabs.",
    stage: "later",
    round: "Series B, Mar 2024",
    where: "New York",
  },
  {
    id: "decart",
    name: "Decart",
    href: "https://decart.ai",
    why: "Live video, restyled while it plays.",
    stage: "later",
    round: "$100M, July 2025",
    where: "Israel",
  },
  {
    id: "recraft",
    name: "Recraft",
    href: "https://www.recraft.ai",
    why: "Vectors and a brand style, from a prompt. The first AI designer seat on the list.",
    stage: "later",
    round: "Series B, May 2025",
    where: "London",
  },
  {
    id: "meticulous",
    name: "Meticulous",
    href: "https://www.meticulous.ai",
    why: "A pixel-level preview of a change, before it merges.",
    stage: "later",
    round: "Series A, July 2026",
    where: "London",
  },
  {
    id: "screen-studio",
    name: "Screen Studio",
    href: "https://screen.studio",
    why: "A small team in Poland. No public round. The recorder designers already use.",
    where: "Poland",
  },
  {
    id: "marker",
    name: "Marker",
    href: "https://marker.page",
    why: "A writing space that stays with the writer. The product designer seat is the London hub.",
    where: "London",
  },
]
