import type { Company } from "@/lib/company"

/**
 * Company list, 3 Oct 2026.
 * The tools on the machine, early teams in the same corner,
 * then the Fast Company 2026 AI pass.
 * Stage is the last public round. The check is stage-check.md.
 * Place and how they work are copied only when a posting or a round already said them.
 * Pre-seed is empty until a public pre-seed round is in hand.
 * The AI names left off are recorded in roadmap.md.
 * Recraft was filed the same day, from the company site and their Series B post.
 * The AI designer seat stayed off the role list. The place is four countries, and the seat grades taste on the model.
 * Marker and Meticulous were filed the same evening.
 * Marker’s seed is in the press, not on their site, so the stage stays off.
 * Wise was filed on 4 Oct 2026. Roy uses the account, and the company is in London.
 * The stage is later. Their own post is the Nasdaq listing of 11 May 2026.
 * How they work stays off. The design postings do not say remote, hybrid, or in the room.
 * The why on each company is that site's own description, copied 4 Oct 2026.
 * A personal note does not belong on the row. A stranger has to be able to read it.
 */
export const companies: Company[] = [
  {
    id: "onlook",
    name: "Onlook",
    href: "https://onlook.com",
    why: "Onlook is a free, local-first editor where designers craft exceptional experiences in code.",
    stage: "seed",
    round: "YC, Winter 2025",
    where: "San Francisco",
  },
  {
    id: "semiotic",
    name: "Semiotic",
    href: "https://semiotic.com",
    why: "Lighthouse is a physical room recorder from Semiotic that turns office conversations into searchable company memory, with controls for what gets saved and who can see it.",
    stage: "seed",
    round: "YC, Fall 2025",
    where: "San Francisco",
  },
  {
    id: "tldraw",
    name: "tldraw",
    href: "https://tldraw.com",
    why: "A free and instant virtual whiteboarding with online collaboration. No signup required. Works on all devices: mobile, tablets, and desktop.",
    stage: "later",
    round: "Series A, Apr 2025",
    work: "hybrid",
    where: "London, hybrid",
  },
  {
    id: "amie",
    name: "Amie",
    href: "https://amie.so",
    why: "Turn meeting notes into automated workflows. Handle meetings, summaries, todos and emails (soon) with your AI personal assistant.",
    stage: "seed",
    round: "Seed, 2022",
  },
  {
    id: "opal",
    name: "Opal",
    href: "https://www.opal.so",
    why: "Real Focus in Real-Time. Measure and improve your focus day by day, on iPhone, iPad and macOS.",
    stage: "seed",
    round: "$10M, May 2026",
  },
  {
    id: "figma",
    name: "Figma",
    href: "https://www.figma.com",
    why: "Figma is the canvas where design, code, and AI come together. From first idea to shipped product — go from concept to production with your whole team, in one place.",
    stage: "later",
  },
  {
    id: "openai",
    name: "OpenAI",
    href: "https://openai.com",
    why: "We believe our research will eventually lead to artificial general intelligence, a system that can solve human-level problems.",
    stage: "later",
  },
  {
    id: "xai",
    name: "xAI",
    href: "https://x.ai",
    why: "SpaceXAI builds Grok — frontier AI models for reasoning, voice, image generation, and more. Build with the Grok API.",
    stage: "later",
  },
  {
    id: "x",
    name: "X",
    href: "https://x.com",
    why: "From breaking news and entertainment to sports and politics, get the full story with all the live commentary.",
    stage: "later",
  },
  {
    id: "cursor",
    name: "Cursor",
    href: "https://cursor.com",
    why: "Built to make you extraordinarily productive, agents turn ideas into code. Accelerate development by handing off tasks to Cursor.",
    stage: "later",
    round: "Series D, Nov 2025",
  },
  {
    id: "vercel",
    name: "Vercel",
    href: "https://vercel.com",
    why: "The autonomous stack for every app and agent.",
    stage: "later",
    round: "Series F, Sep 2025",
  },
  {
    id: "cosmos",
    name: "Cosmos",
    href: "https://www.cosmos.so",
    why: "Your space for inspiration",
    stage: "later",
    round: "Series A, Jan 2026",
    where: "New York",
  },
  {
    id: "granola",
    name: "Granola",
    href: "https://www.granola.ai",
    why: "The AI notepad for back-to-back meetings. Notes, actions and memory. Without a meeting bot.",
    stage: "later",
    round: "Series C, Mar 2026",
    work: "room",
    where: "London, onsite",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    href: "https://elevenlabs.io",
    why: "Create lifelike speech with our AI voice generator and voice agents platform. Access 5,000+ voices in 70+ languages with secure APIs and SDKs.",
    stage: "later",
    round: "Series C, Jan 2025",
    work: "remote",
    where: "Remote",
  },
  {
    id: "paper",
    name: "Paper",
    href: "https://paper.design",
    why: "Paper is a modern and powerful design tool that helps you create, share, and ship your best work.",
    stage: "later",
    round: "Series A, Jul 2026",
    work: "remote",
    where: "Remote, Americas, Europe, and Australia",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    href: "https://www.anthropic.com",
    why: "Anthropic is an AI safety and research company that's working to build reliable, interpretable, and steerable AI systems.",
    stage: "later",
    where: "San Francisco",
  },
  {
    id: "world-labs",
    name: "World Labs",
    href: "https://www.worldlabs.ai",
    why: "World Labs is a spatial intelligence company, building frontier models that can perceive, generate, and interact with the 3D world.",
    stage: "later",
    round: "$1B, Feb 2026",
  },
  {
    id: "runway",
    name: "Runway",
    href: "https://runwayml.com",
    why: "Runway is building foundational Real-World Intelligence that can understand, simulate and act in the world. We offer products and services built on-top of this intelligence to empower individuals and organizations to do more in the world.",
    stage: "later",
    round: "$315M, Feb 2026",
  },
  {
    id: "factory",
    name: "Factory",
    href: "https://factory.ai",
    why: "Build faster with AI coding agents. Factory Droids automate coding, testing, and deployment for startups and enterprises.",
    stage: "later",
    round: "$200M, Sep 2026",
    where: "San Francisco",
  },
  {
    id: "hume",
    name: "Hume",
    href: "https://www.hume.ai",
    why: "Real human ratings, in a single API call. The human evaluation layer for voice, speech, and conversational AI.",
    stage: "later",
    round: "Series B, Mar 2024",
    where: "New York",
  },
  {
    id: "decart",
    name: "Decart",
    href: "https://decart.ai",
    why: "Decart is a frontier AI lab building real-time world models — environments that respond instantly and run at millisecond latency with unprecedented efficiency.",
    stage: "later",
    round: "$100M, July 2025",
    where: "Israel",
  },
  {
    id: "recraft",
    name: "Recraft",
    href: "https://www.recraft.ai",
    why: "Recraft is a top-ranked text-to-image model and design platform for photorealism, vector generation, custom styles, mockups, and more.",
    stage: "later",
    round: "Series B, May 2025",
    where: "London",
  },
  {
    id: "meticulous",
    name: "Meticulous",
    href: "https://www.meticulous.ai",
    why: "Meticulous auto-generates and auto-maintains visual frontend browser tests, providing a level of coverage that is unattainable with manually written tests.",
    stage: "later",
    round: "Series A, July 2026",
    where: "London",
  },
  {
    id: "screen-studio",
    name: "Screen Studio",
    href: "https://screen.studio",
    why: "Screen recorder for macOS. Create engaging product demos, courses, tutorial and social media videos. Add automatic zoom on mouse actions, smooth mouse movement, and other powerful effects and animations. Designed for macOS.",
    where: "Poland",
  },
  {
    id: "marker",
    name: "Marker",
    href: "https://marker.page",
    why: "Marker is a writing tool for people who believe in writing. Write with us.",
    where: "London",
  },
  {
    id: "wise",
    name: "Wise",
    href: "https://wise.com",
    why: "150+ countries, 40 currencies, one account. Save when you send, spend and manage your money internationally.",
    stage: "later",
    round: "Nasdaq, May 2026",
    where: "London",
  },
]
